import { createHash } from "node:crypto";

export interface EventCatalogSeedItem {
  id: string;
  slug: string;
  title: string;
  summary: string;
  aliases: readonly string[];
  tags: readonly string[];
  kind: string;
  status: "active";
  geographicScope: "country" | "global" | "city";
  countries: readonly string[];
  subdivisions: readonly string[];
  city: string | null;
  online: boolean;
  trustTier: "official" | "authoritative";
  dateCertainty: "confirmed" | "tentative" | "calculated";
  provenanceUrl: string;
  sourceRevision: "seed-2026-07-18" | "seed-2026-07-18-v2";
  checkedAt: "2026-07-18T00:00:00.000Z" | "2026-07-18T06:30:00.000Z";
  freshnessSlaHours: number;
  rightsBasis: "metadata_only" | "source_terms" | "cc_by_4_0";
  termsUrl: string | null;
  attribution: string;
  connectorType: string;
  connectorReference: string;
}

const common = {
  status: "active" as const,
  sourceRevision: "seed-2026-07-18" as const,
  checkedAt: "2026-07-18T00:00:00.000Z" as const,
};

const DATE_CONFIRMABLE_KINDS = new Set([
  "country_holidays",
  "regional_calendar",
]);

type CatalogSourceInput = Omit<
  EventCatalogSeedItem,
  | "id"
  | "status"
  | "sourceRevision"
  | "checkedAt"
  | "aliases"
  | "subdivisions"
  | "city"
  | "online"
  | "termsUrl"
  | "connectorReference"
> & {
  aliases?: readonly string[];
  subdivisions?: readonly string[];
  city?: string | null;
  online?: boolean;
  termsUrl?: string | null;
  connectorReference?: string;
};

function catalogSource(input: CatalogSourceInput): EventCatalogSeedItem {
  return {
    ...input,
    id: `catalog-${input.slug}`,
    status: "active",
    sourceRevision: "seed-2026-07-18-v2",
    checkedAt: "2026-07-18T06:30:00.000Z",
    aliases: input.aliases ?? [],
    subdivisions: input.subdivisions ?? [],
    city: input.city ?? null,
    online: input.online ?? false,
    // A mutable source listing is not proof that each future occurrence is final.
    dateCertainty:
      input.dateCertainty === "calculated" ||
      DATE_CONFIRMABLE_KINDS.has(input.kind)
        ? input.dateCertainty
        : "tentative",
    termsUrl: input.termsUrl ?? null,
    connectorReference: input.connectorReference ?? input.slug,
  };
}

export const EVENT_CATALOG_SEED_MANIFEST: readonly EventCatalogSeedItem[] = [
  {
    ...common,
    id: "catalog-uae-public-holidays",
    slug: "uae-public-holidays",
    title: "UAE public holidays",
    summary:
      "Official public holiday announcements for the United Arab Emirates.",
    aliases: ["united arab emirates holidays"],
    tags: ["holidays", "uae", "government"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["AE"],
    subdivisions: [],
    city: null,
    online: false,
    trustTier: "official",
    dateCertainty: "tentative",
    provenanceUrl:
      "https://u.ae/en/information-and-services/public-holidays-and-religious-affairs/public-holidays",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    termsUrl: null,
    attribution: "United Arab Emirates Government",
    connectorType: "official_page",
    connectorReference: "uae-government-public-holidays",
  },
  {
    ...common,
    id: "catalog-un-international-days",
    slug: "un-international-days",
    title: "UN International Days and Weeks",
    summary: "International observances designated by the United Nations.",
    aliases: ["un observances", "united nations international days"],
    tags: ["global", "international", "observances", "un"],
    kind: "global_celebrations",
    geographicScope: "global",
    countries: [],
    subdivisions: [],
    city: null,
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.un.org/en/observances/list-days-weeks",
    freshnessSlaHours: 720,
    rightsBasis: "source_terms",
    termsUrl: "https://www.un.org/en/about-us/terms-of-use",
    attribution: "United Nations",
    connectorType: "official_page",
    connectorReference: "un-international-days",
  },
  {
    ...common,
    id: "catalog-jewish-holidays-diaspora",
    slug: "jewish-holidays-diaspora",
    title: "Jewish holidays (Diaspora)",
    summary: "Jewish holiday dates for communities outside Israel.",
    aliases: ["hebcal diaspora holidays"],
    tags: ["diaspora", "jewish", "religious"],
    kind: "religious_observances",
    geographicScope: "global",
    countries: [],
    subdivisions: [],
    city: null,
    online: false,
    trustTier: "authoritative",
    dateCertainty: "calculated",
    provenanceUrl: "https://www.hebcal.com/holidays/",
    freshnessSlaHours: 720,
    rightsBasis: "cc_by_4_0",
    termsUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "Hebcal.com",
    connectorType: "hebcal_api",
    connectorReference: "hebcal-diaspora",
  },
  {
    ...common,
    id: "catalog-jewish-holidays-israel",
    slug: "jewish-holidays-israel",
    title: "Jewish holidays (Israel)",
    summary: "Jewish holiday dates using the Israeli holiday schedule.",
    aliases: ["hebcal israel holidays"],
    tags: ["israel", "jewish", "religious"],
    kind: "religious_observances",
    geographicScope: "country",
    countries: ["IL"],
    subdivisions: [],
    city: null,
    online: false,
    trustTier: "authoritative",
    dateCertainty: "calculated",
    provenanceUrl: "https://www.hebcal.com/holidays/",
    freshnessSlaHours: 720,
    rightsBasis: "cc_by_4_0",
    termsUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "Hebcal.com",
    connectorType: "hebcal_api",
    connectorReference: "hebcal-israel",
  },
  {
    ...common,
    id: "catalog-gitex-global",
    slug: "gitex-global",
    title: "GITEX Global",
    summary: "Official GITEX Global technology conference announcements.",
    aliases: ["gitex"],
    tags: ["ai", "business", "conference", "technology"],
    kind: "conference_series",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    online: false,
    trustTier: "official",
    dateCertainty: "tentative",
    provenanceUrl: "https://www.gitex.com/",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    termsUrl: null,
    attribution: "Dubai World Trade Centre",
    connectorType: "official_page",
    connectorReference: "gitex-global",
  },
  {
    ...common,
    id: "catalog-ai-everything-global",
    slug: "ai-everything-global",
    title: "AI Everything Global",
    summary: "Official AI Everything Global conference announcements.",
    aliases: ["ai everything"],
    tags: ["ai", "business", "conference", "technology"],
    kind: "conference_series",
    geographicScope: "country",
    countries: ["AE"],
    subdivisions: [],
    city: null,
    online: false,
    trustTier: "official",
    dateCertainty: "tentative",
    provenanceUrl: "https://www.aieverythingglobal.com/",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    termsUrl: null,
    attribution: "Dubai World Trade Centre",
    connectorType: "official_page",
    connectorReference: "ai-everything-global",
  },
  catalogSource({
    slug: "openholidays",
    title: "OpenHolidays",
    summary:
      "Open public and school holiday calendars for supported countries and subdivisions.",
    aliases: ["open holidays api"],
    tags: ["holidays", "open-data", "school-holidays"],
    kind: "country_holidays",
    geographicScope: "global",
    countries: [],
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.openholidaysapi.org/en/api/",
    freshnessSlaHours: 168,
    rightsBasis: "source_terms",
    termsUrl: "https://www.openholidaysapi.org/en/faq/",
    attribution: "OpenHolidays API",
    connectorType: "openholidays_api",
  }),
  catalogSource({
    slug: "gov-uk-bank-holidays",
    title: "GOV.UK bank holidays",
    summary:
      "Official bank holidays for England and Wales, Scotland, and Northern Ireland.",
    aliases: ["uk bank holidays"],
    tags: ["government", "holidays", "united-kingdom"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["GB"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.api.gov.uk/gds/bank-holidays/",
    freshnessSlaHours: 24,
    rightsBasis: "source_terms",
    termsUrl:
      "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
    attribution: "UK Government",
    connectorType: "gov_uk_api",
  }),
  catalogSource({
    slug: "france-public-holidays",
    title: "French public holidays",
    summary:
      "Official public holidays for metropolitan France and overseas territories.",
    aliases: ["jours feries france"],
    tags: ["france", "government", "holidays"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["FR"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.data.gouv.fr/dataservices/jours-feries",
    freshnessSlaHours: 24,
    rightsBasis: "source_terms",
    termsUrl: "https://www.etalab.gouv.fr/licence-ouverte-open-licence/",
    attribution: "French Government",
    connectorType: "data_gouv_api",
  }),
  catalogSource({
    slug: "singapore-public-holidays",
    title: "Singapore public holidays",
    summary:
      "Official public holiday dates published by Singapore's Ministry of Manpower.",
    aliases: ["singapore mom holidays"],
    tags: ["government", "holidays", "singapore"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["SG"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://data.gov.sg/datasets?resultId=691&sort=updatedAt",
    freshnessSlaHours: 24,
    rightsBasis: "source_terms",
    termsUrl: "https://data.gov.sg/open-data-licence",
    attribution: "Singapore Ministry of Manpower",
    connectorType: "data_gov_sg_api",
  }),
  catalogSource({
    slug: "australia-public-holidays",
    title: "Australian public holidays",
    summary:
      "Government-published national and state or territory holiday dates for Australia.",
    aliases: ["australian holidays"],
    tags: ["australia", "government", "holidays"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["AU"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl:
      "https://data.gov.au/data/dataset/australian-holidays-machine-readable-dataset",
    freshnessSlaHours: 168,
    rightsBasis: "source_terms",
    termsUrl: "https://creativecommons.org/licenses/by/3.0/au/",
    attribution: "Australian Government",
    connectorType: "data_gov_au_dataset",
  }),
  catalogSource({
    slug: "hong-kong-public-holidays",
    title: "Hong Kong public holidays",
    summary:
      "Official general holiday dates published by the Hong Kong Government.",
    aliases: ["hong kong general holidays"],
    tags: ["government", "holidays", "hong-kong"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["HK"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://data.gov.hk/en-data/dataset/hk-dpo-statistic-cal",
    freshnessSlaHours: 168,
    rightsBasis: "source_terms",
    termsUrl: "https://data.gov.hk/en/terms-and-conditions",
    attribution: "Hong Kong Government",
    connectorType: "data_gov_hk_dataset",
  }),
  catalogSource({
    slug: "us-federal-holidays",
    title: "US federal holidays",
    summary:
      "Federal holiday dates published by the United States Office of Personnel Management.",
    aliases: ["opm federal holidays"],
    tags: ["government", "holidays", "united-states"],
    kind: "country_holidays",
    geographicScope: "country",
    countries: ["US"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl:
      "https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    attribution: "US Office of Personnel Management",
    connectorType: "official_ics",
  }),
  catalogSource({
    slug: "victoria-important-dates",
    title: "Victoria important dates",
    summary:
      "Public holidays, school terms, daylight saving, and multifaith dates for Victoria.",
    aliases: ["victoria government dates"],
    tags: ["australia", "holidays", "multifaith", "school-terms"],
    kind: "regional_calendar",
    geographicScope: "country",
    countries: ["AU"],
    subdivisions: ["AU-VIC"],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl:
      "https://discover.data.vic.gov.au/dataset/government-dates-api-data",
    freshnessSlaHours: 720,
    rightsBasis: "cc_by_4_0",
    termsUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "State Government of Victoria",
    connectorType: "victoria_dates_api",
  }),
  catalogSource({
    slug: "python-events",
    title: "Python events",
    summary:
      "Python conferences and community group events published by the Python Software Foundation.",
    aliases: ["python conferences", "python user group events"],
    tags: ["conference", "developer", "python", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.python.org/events/",
    freshnessSlaHours: 24,
    rightsBasis: "source_terms",
    termsUrl: "https://www.python.org/about/legal/",
    attribution: "Python Software Foundation",
    connectorType: "official_ics",
  }),
  catalogSource({
    slug: "wikidata-event-topics",
    title: "Wikidata event topics",
    summary:
      "Open identifiers and aliases used to enrich event topics without treating them as date authority.",
    aliases: ["wikidata events"],
    tags: ["aliases", "identifiers", "open-data", "topics"],
    kind: "catalog_enrichment",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "authoritative",
    dateCertainty: "calculated",
    provenanceUrl: "https://www.wikidata.org/wiki/Wikidata:Licensing",
    freshnessSlaHours: 168,
    rightsBasis: "source_terms",
    termsUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Wikidata contributors",
    connectorType: "wikidata_api",
  }),
  catalogSource({
    slug: "bahai-calendar",
    title: "Bahai calendar",
    summary:
      "Official Bahai holy days and calendar observances for reference and following.",
    aliases: ["badi calendar", "bahai holy days"],
    tags: ["bahai", "religious", "worldwide"],
    kind: "religious_observances",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "calculated",
    provenanceUrl: "https://www.bahai.org/action/devotional-life/calendar",
    freshnessSlaHours: 720,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.bahai.org/legal",
    attribution: "Bahai International Community",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "vatican-liturgical-calendar",
    title: "Vatican liturgical calendar",
    summary: "Catholic liturgical celebrations published by the Holy See.",
    aliases: ["catholic celebrations", "vatican calendar"],
    tags: ["catholic", "christian", "religious"],
    kind: "religious_observances",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.vatican.va/content/liturgy/en.html",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    attribution: "The Holy See",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "sgpc-nanakshahi-calendar",
    title: "SGPC Nanakshahi calendar",
    summary:
      "Sikh festivals and commemorations published by the Shiromani Gurdwara Parbandhak Committee.",
    aliases: ["sikh calendar", "nanakshahi calendar"],
    tags: ["religious", "sikh"],
    kind: "religious_observances",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "calculated",
    provenanceUrl: "https://sgpc.net/nanakshahi-calendar/",
    freshnessSlaHours: 720,
    rightsBasis: "metadata_only",
    attribution: "Shiromani Gurdwara Parbandhak Committee",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "linux-foundation-events",
    title: "Linux Foundation events",
    summary:
      "Open-source, cloud native, AI, and developer events organized by the Linux Foundation.",
    aliases: ["kubecon", "open source summit"],
    tags: ["ai", "cloud", "conference", "open-source", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://events.linuxfoundation.org/about/calendar/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "The Linux Foundation",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "aws-events",
    title: "AWS events",
    summary:
      "Cloud, AI, developer, and business events organized by Amazon Web Services.",
    aliases: ["aws summit", "aws re invent"],
    tags: ["ai", "aws", "cloud", "conference", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://aws.amazon.com/events/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://aws.amazon.com/terms/",
    attribution: "Amazon Web Services",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "google-developer-events",
    title: "Google developer events",
    summary:
      "Google I/O, Cloud Next, DevFest, and developer workshops from official Google channels.",
    aliases: ["google io", "google cloud next", "devfest"],
    tags: ["cloud", "conference", "developer", "google", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://developers.google.com/events/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Google",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "microsoft-events",
    title: "Microsoft events",
    summary:
      "Microsoft Build, Ignite, Reactor, and business events from official Microsoft channels.",
    aliases: ["microsoft build", "microsoft ignite", "microsoft reactor"],
    tags: ["cloud", "conference", "developer", "microsoft", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://events.microsoft.com/allevents",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.microsoft.com/en-us/legal/terms-of-use",
    attribution: "Microsoft",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "github-events",
    title: "GitHub events",
    summary:
      "GitHub Universe, webinars, and regional developer events from official GitHub channels.",
    aliases: ["github universe", "github webinars"],
    tags: ["conference", "developer", "github", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://github.com/resources/events",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl:
      "https://docs.github.com/en/site-policy/github-terms/github-terms-of-service",
    attribution: "GitHub",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "apple-developer-events",
    title: "Apple developer events",
    summary:
      "WWDC, developer labs, workshops, and activities published by Apple.",
    aliases: ["wwdc", "apple developer activities"],
    tags: ["apple", "conference", "developer", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://developer.apple.com/events/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Apple",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "nvidia-events",
    title: "NVIDIA events",
    summary:
      "GTC and other AI and accelerated computing events published by NVIDIA.",
    aliases: ["nvidia gtc"],
    tags: ["ai", "conference", "developer", "nvidia", "technology"],
    kind: "conference_series",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.nvidia.com/gtc/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.nvidia.com/en-us/about-nvidia/legal-info/",
    attribution: "NVIDIA",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "dubai-calendar",
    title: "Dubai Calendar",
    summary:
      "Dubai concerts, culture, sport, family activities, and festivals from the official city calendar.",
    aliases: ["dubai events calendar", "visit dubai events"],
    tags: ["culture", "dubai", "family", "music", "sports"],
    kind: "city_events",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl:
      "https://www.visitdubai.com/en/festivals-and-events/dubai-events-calendar",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.visitdubai.com/en/terms-of-use-dubai-calendar-app",
    attribution: "Dubai Department of Economy and Tourism",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "dubai-world-trade-centre-events",
    title: "Dubai World Trade Centre events",
    summary:
      "Exhibitions, conferences, and public events hosted at Dubai World Trade Centre.",
    aliases: ["dwtc events"],
    tags: ["business", "conference", "dubai", "exhibition"],
    kind: "venue_calendar",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.dwtc.com/en/events/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.dwtc.com/en/terms/",
    attribution: "Dubai World Trade Centre",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "experience-abu-dhabi-events",
    title: "Experience Abu Dhabi events",
    summary:
      "Abu Dhabi culture, sport, entertainment, and festival listings from the official tourism platform.",
    aliases: ["visit abu dhabi events"],
    tags: ["abu-dhabi", "culture", "festival", "sports"],
    kind: "city_events",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-AZ"],
    city: "Abu Dhabi",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://visitabudhabi.ae/en/events",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://visitabudhabi.ae/en/terms-and-conditions",
    attribution: "Department of Culture and Tourism Abu Dhabi",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "dubai-business-events",
    title: "Dubai business events",
    summary:
      "Conferences, congresses, and professional events listed by Dubai's official business events bureau.",
    aliases: ["dubai mice events"],
    tags: ["business", "conference", "dubai", "networking"],
    kind: "conference_series",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.visitdubai.com/en/mice/events-calendar",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Dubai Business Events",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "expo-city-dubai-events",
    title: "Expo City Dubai events",
    summary:
      "Community, sustainability, culture, and family events at Expo City Dubai.",
    aliases: ["expo city events"],
    tags: ["community", "culture", "dubai", "family", "sustainability"],
    kind: "venue_calendar",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.expocitydubai.com/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.expocitydubai.com/en/ticket-terms/",
    attribution: "Expo City Dubai",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "dubai-opera-events",
    title: "Dubai Opera events",
    summary:
      "Opera, theatre, dance, concerts, and performing arts at Dubai Opera.",
    aliases: ["dubai opera calendar"],
    tags: ["arts", "culture", "dubai", "music", "theatre"],
    kind: "venue_calendar",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.dubaiopera.com/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Dubai Opera",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "louvre-abu-dhabi-events",
    title: "Louvre Abu Dhabi events",
    summary:
      "Exhibitions, talks, workshops, and performances at Louvre Abu Dhabi.",
    aliases: ["louvre abu dhabi calendar"],
    tags: ["abu-dhabi", "art", "culture", "museum"],
    kind: "venue_calendar",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-AZ"],
    city: "Abu Dhabi",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.louvreabudhabi.ae/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Louvre Abu Dhabi",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "dubai-culture-events",
    title: "Dubai Culture events",
    summary:
      "Museums, heritage, literature, and cultural programs from Dubai Culture.",
    aliases: ["dubai culture calendar"],
    tags: ["culture", "dubai", "heritage", "literature", "museum"],
    kind: "city_events",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://dubaiculture.gov.ae/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Dubai Culture and Arts Authority",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "art-dubai",
    title: "Art Dubai",
    summary:
      "Art fairs, talks, commissions, and cultural programs organized by Art Dubai.",
    aliases: ["art dubai fair"],
    tags: ["art", "culture", "dubai", "fair"],
    kind: "festival_series",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.artdubai.ae/",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    attribution: "Art Dubai",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "alserkal-avenue-events",
    title: "Alserkal Avenue events",
    summary:
      "Art, cinema, workshops, talks, and community events at Alserkal Avenue.",
    aliases: ["alserkal events"],
    tags: ["art", "cinema", "community", "dubai", "workshops"],
    kind: "venue_calendar",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://alserkal.online/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Alserkal Avenue",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "fia-motorsport-calendar",
    title: "FIA motorsport calendar",
    summary:
      "Formula, endurance, rally, and other motorsport competitions sanctioned by the FIA.",
    aliases: ["fia calendar", "formula one calendar"],
    tags: ["formula-one", "motorsport", "racing", "sports"],
    kind: "sports_calendar",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.fia.com/calendar",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Federation Internationale de l'Automobile",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "world-athletics-calendar",
    title: "World Athletics calendar",
    summary: "International athletics competitions listed by World Athletics.",
    aliases: ["athletics competition calendar"],
    tags: ["athletics", "running", "sports", "track-and-field"],
    kind: "sports_calendar",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://worldathletics.org/competition/calendar-results",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "World Athletics",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "atp-tour-calendar",
    title: "ATP Tour calendar",
    summary: "Men's professional tennis tournaments listed by the ATP Tour.",
    aliases: ["atp tournaments"],
    tags: ["sports", "tennis"],
    kind: "sports_calendar",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.atptour.com/en/tournaments/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.atptour.com/en/terms-and-conditions-app",
    attribution: "ATP Tour",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "wta-tour-calendar",
    title: "WTA Tour calendar",
    summary: "Women's professional tennis tournaments listed by the WTA Tour.",
    aliases: ["wta tournaments"],
    tags: ["sports", "tennis"],
    kind: "sports_calendar",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.wtatennis.com/tournaments",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "WTA Tour",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "olympic-events",
    title: "Olympic events",
    summary:
      "Olympic and Youth Olympic event cycles from official Olympic channels.",
    aliases: ["olympics calendar", "youth olympics"],
    tags: ["olympics", "sports"],
    kind: "sports_calendar",
    geographicScope: "global",
    countries: [],
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://olympics.com/",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    termsUrl: "https://newsroom.olympics.com/terms_and_conditions",
    attribution: "International Olympic Committee",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "dubai-sports-council-events",
    title: "Dubai Sports Council events",
    summary:
      "Participatory and professional sports events supported by Dubai Sports Council.",
    aliases: ["dubai sports events"],
    tags: ["community", "dubai", "fitness", "sports"],
    kind: "city_events",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-DU"],
    city: "Dubai",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.dubaisc.ae/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Dubai Sports Council",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "abu-dhabi-sports-council-events",
    title: "Abu Dhabi Sports Council events",
    summary:
      "Professional and community sports events supported by Abu Dhabi Sports Council.",
    aliases: ["abu dhabi sports events"],
    tags: ["abu-dhabi", "community", "fitness", "sports"],
    kind: "city_events",
    geographicScope: "city",
    countries: ["AE"],
    subdivisions: ["AE-AZ"],
    city: "Abu Dhabi",
    trustTier: "official",
    dateCertainty: "confirmed",
    provenanceUrl: "https://adsc.gov.ae/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Abu Dhabi Sports Council",
    connectorType: "official_page",
  }),
  catalogSource({
    slug: "ticketmaster-discovery",
    title: "Ticketmaster Discovery",
    summary:
      "Concert, sports, arts, and venue event discovery available through an approved Ticketmaster API agreement.",
    aliases: ["ticketmaster events"],
    tags: ["agreement-required", "arts", "concerts", "sports", "ticketing"],
    kind: "commercial_discovery",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl:
      "https://developer.ticketmaster.com/products-and-docs/apis/discovery-manual/v2/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl:
      "https://developer.ticketmaster.com/support/terms-of-use/partner/",
    attribution: "Ticketmaster",
    connectorType: "agreement_required_api",
  }),
  catalogSource({
    slug: "predicthq",
    title: "PredictHQ",
    summary:
      "Broad global event intelligence available through a commercial PredictHQ data agreement.",
    aliases: ["predict hq events"],
    tags: ["agreement-required", "commercial", "event-intelligence", "global"],
    kind: "commercial_discovery",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl: "https://docs.predicthq.com/api",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "PredictHQ",
    connectorType: "agreement_required_api",
  }),
  catalogSource({
    slug: "eventbrite-organizer-events",
    title: "Eventbrite organizer events",
    summary:
      "Events belonging to an authorized Eventbrite organizer account through the official API.",
    aliases: ["eventbrite events"],
    tags: ["agreement-required", "community", "organizer", "ticketing"],
    kind: "account_events",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.eventbrite.com/platform/docs/api-basics",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.eventbrite.com/corporate/legal/legalterms/",
    attribution: "Eventbrite",
    connectorType: "agreement_required_api",
  }),
  catalogSource({
    slug: "meetup-groups",
    title: "Meetup groups",
    summary:
      "Professional, hobby, learning, and social group events from user-authorized Meetup sources.",
    aliases: ["meetup events"],
    tags: [
      "agreement-required",
      "community",
      "hobbies",
      "learning",
      "networking",
    ],
    kind: "account_events",
    geographicScope: "global",
    countries: [],
    online: true,
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.meetup.com/api/",
    freshnessSlaHours: 24,
    rightsBasis: "metadata_only",
    attribution: "Meetup",
    connectorType: "agreement_required_api",
  }),
  catalogSource({
    slug: "timeanddate-holidays",
    title: "timeanddate holidays API",
    summary:
      "Commercial worldwide holiday coverage available through a licensed timeanddate API plan.",
    aliases: ["time and date holidays"],
    tags: ["agreement-required", "commercial", "holidays"],
    kind: "country_holidays",
    geographicScope: "global",
    countries: [],
    trustTier: "authoritative",
    dateCertainty: "confirmed",
    provenanceUrl: "https://www.timeanddate.com/services/api/",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    termsUrl: "https://www.timeanddate.com/information/copyright.html",
    attribution: "timeanddate.com",
    connectorType: "agreement_required_api",
  }),
  catalogSource({
    slug: "nager-date-holidays",
    title: "Nager.Date holidays",
    summary:
      "Calculated country holiday coverage requiring a separate review of hosted data and offline licensing.",
    aliases: ["nager date"],
    tags: ["agreement-required", "calculated", "holidays"],
    kind: "country_holidays",
    geographicScope: "global",
    countries: [],
    trustTier: "authoritative",
    dateCertainty: "calculated",
    provenanceUrl: "https://github.com/nager/Nager.Date",
    freshnessSlaHours: 168,
    rightsBasis: "metadata_only",
    attribution: "Nager.Date",
    connectorType: "agreement_required_api",
  }),
];

export function eventCatalogSeedContentHash(
  item: EventCatalogSeedItem
): string {
  return createHash("sha256").update(JSON.stringify(item)).digest("hex");
}
